import { useEffect, useState } from "react";
import { ArrowRight, Cloud, Link2, Plus, Trash2 } from "lucide-react";
import { createOneDriveSourceFromUrl, deleteCloudSource, listCloudSources } from "../../services/api";
import type { CloudSource, CloudSourceType } from "../../types/project";
interface Props { projectId:string|null; onReturnHome:()=>void; }
const providerLabels={google_drive:"Google Drive",onedrive:"OneDrive"} as const;
export default function CloudSources({projectId,onReturnHome}:Props){
 const [items,setItems]=useState<CloudSource[]>([]); const [displayName,setDisplayName]=useState(""); const [webUrl,setWebUrl]=useState(""); const [sourceType,setSourceType]=useState<CloudSourceType>("file"); const [error,setError]=useState(""); const [message,setMessage]=useState("");
 useEffect(()=>{void listCloudSources().then(setItems).catch(()=>setError("تعذر تحميل مصادر السحابة."));},[]);
 async function add(){if(!displayName.trim()||!webUrl.trim()){setError("الاسم والرابط مطلوبان.");return;} setError("");setMessage("");try{const created=await createOneDriveSourceFromUrl({displayName:displayName.trim(),webUrl:webUrl.trim(),sourceProjectId:projectId,sourceType});setItems(v=>[created,...v]);setDisplayName("");setWebUrl("");setMessage("تم حفظ مصدر OneDrive.");}catch{setError("تعذر حفظ الرابط. تأكد أنه رابط OneDrive أو SharePoint صالح.");}}
 async function remove(id:string){try{await deleteCloudSource(id);setItems(v=>v.filter(x=>x.id!==id));}catch{setError("تعذر حذف المصدر.");}}
 return <main className="cloud-sources" dir="rtl"><header className="cloud-sources-header"><div><span><Cloud size={18}/> مصادر السحابة</span><h1>ربط مصادر Google Drive وOneDrive</h1><p>أضف المصدر الآن، ثم تأتي المصادقة والمزامنة الفعلية في المراحل التالية.</p></div><button className="secondary-button" onClick={onReturnHome}><ArrowRight size={18}/> العودة</button></header><section className="cloud-source-form"><h2>إضافة مصدر OneDrive</h2><div><input placeholder="اسم المصدر" value={displayName} onChange={e=>setDisplayName(e.target.value)}/><select value={sourceType} onChange={e=>setSourceType(e.target.value as CloudSourceType)}><option value="file">ملف</option><option value="folder">مجلد</option></select><input className="cloud-source-url" placeholder="رابط OneDrive أو SharePoint" value={webUrl} onChange={e=>setWebUrl(e.target.value)}/></div><button className="primary-button" onClick={()=>void add()}><Plus size={17}/> حفظ المصدر</button></section>{message?<div className="cloud-source-message">{message}</div>:null}{error?<div className="cloud-source-error">{error}</div>:null}<section className="cloud-source-list"><h2>المصادر المحفوظة</h2>{items.length?items.map(item=><article key={item.id}><div><span>{providerLabels[item.provider]}</span><h3>{item.displayName}</h3></div><p>النوع: {item.sourceType==="file"?"ملف":"مجلد"}</p><p>الحالة: {item.syncStatus}</p><a href={item.webUrl} target="_blank" rel="noreferrer"><Link2 size={15}/> فتح المصدر</a><button className="secondary-button compact" onClick={()=>void remove(item.id)}><Trash2 size={15}/> حذف</button></article>):<p>لا توجد مصادر سحابية محفوظة.</p>}</section></main>;
}
