import { useEffect, useState } from "react";
import { ArrowRight, Layers3, Plus, Trash2 } from "lucide-react";
import { createDifferentiatedActivity, deleteDifferentiatedActivity, listDifferentiatedActivities } from "../../services/api";
import type { DifferentiatedActivity, DifferentiationLevel, ScienceDomain } from "../../types/project";
interface Props { projectId: string | null; onReturnHome: () => void; }
const labels: Record<DifferentiationLevel,string> = { support:"دعم", core:"أساسي", extension:"إثراء" };
export default function DifferentiatedActivities({projectId,onReturnHome}:Props){
 const [items,setItems]=useState<DifferentiatedActivity[]>([]); const [title,setTitle]=useState(""); const [objective,setObjective]=useState(""); const [instructions,setInstructions]=useState(""); const [level,setLevel]=useState<DifferentiationLevel>("core"); const [error,setError]=useState("");
 useEffect(()=>{void listDifferentiatedActivities().then(setItems).catch(()=>setError("تعذر تحميل الأنشطة."));},[]);
 async function save(){if(!title.trim()||!objective.trim()||!instructions.trim()){setError("العنوان والهدف والتعليمات مطلوبة.");return;} try{const x=await createDifferentiatedActivity({sourceProjectId:projectId,title,grade:10,scienceDomain:"physics" as ScienceDomain,subjectId:"g10-physics",level,objective,instructions,estimatedMinutes:20});setItems(v=>[x,...v]);setTitle("");setObjective("");setInstructions("");setError("");}catch{setError("تعذر حفظ النشاط.");}}
 async function remove(id:string){try{await deleteDifferentiatedActivity(id);setItems(v=>v.filter(x=>x.id!==id));}catch{setError("تعذر حذف النشاط.");}}
 return <main className="differentiated-activities" dir="rtl"><header className="differentiated-header"><div><span><Layers3 size={18}/> الأنشطة المتمايزة</span><h1>أنشطة علمية بمستويات دعم مختلفة</h1></div><button className="secondary-button" onClick={onReturnHome}><ArrowRight size={18}/> العودة</button></header><section className="differentiated-form-card"><h2>إنشاء نشاط</h2><div className="differentiated-form-grid"><input placeholder="العنوان" value={title} onChange={e=>setTitle(e.target.value)}/><select value={level} onChange={e=>setLevel(e.target.value as DifferentiationLevel)}><option value="support">دعم</option><option value="core">أساسي</option><option value="extension">إثراء</option></select><textarea placeholder="الهدف" value={objective} onChange={e=>setObjective(e.target.value)}/><textarea placeholder="التعليمات" value={instructions} onChange={e=>setInstructions(e.target.value)}/></div><button className="primary-button" onClick={()=>void save()}><Plus size={17}/> حفظ النشاط</button></section>{error?<div className="differentiated-error">{error}</div>:null}<section className="differentiated-list"><h2>الأنشطة المحفوظة</h2>{items.map(x=><article key={x.id}><div className="differentiated-item-heading"><div><span className={`differentiated-level ${x.level}`}>{labels[x.level]}</span><h3>{x.title}</h3></div><button className="secondary-button compact" onClick={()=>void remove(x.id)}><Trash2 size={15}/> حذف</button></div><p>{x.objective}</p><p>{x.instructions}</p></article>)}</section></main>;
}
